<a href="https://colab.research.google.com/github/dimassa666/Scientific-Computing/blob/main/Sesi_1_Scientific_Computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
x = 1
x

1

In [4]:
x = x + 1
x

2

In [6]:
x = 1
y = x + 1
x = 5
y

2

In [10]:
import numpy as np
x = np.array([1, 4, 3])
y = np.array([[1, 4, 3], [9, 2, 7]])
print(x)
print(y)

[1 4 3]
[[1 4 3]
 [9 2 7]]


In [11]:
def my_adder(a, b, c):
  """
  Function to sum 3 numbers
  input: 3 numbers
  output: the sum of a + b + c
  author: 
  date:
  """

  #this is the summation
  out = a + b + c
  return out

In [12]:
my_adder(10,3,4)

17

In [13]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'OFF'
  return status

In [14]:
my_thermo_stat(65,75)

'heat'

In [15]:
my_thermo_stat(75,65)

'AC'

In [16]:
my_thermo_stat(65,63)

'OFF'

In [19]:
x = 1.5
if x > 1 and x < 2:
  y = 2
elif x > 2 and x < 4:
  y = 4
else:
  y = 0
print(y)

2
